CALL DROP_TABLE ('IBROKER','REP_TABLATEMP_PARAM_COMISIONES');
/
CREATE GLOBAL TEMPORARY TABLE REP_TABLATEMP_PARAM_COMISIONES
(
	ADM_RAMO_ID 				NUMBER(10,0),
	ADM_PRODUCTO_ID 			NUMBER(10,0),
	NOMBRE						VARCHAR2(120) DEFAULT '',
	C_CURRENCY_ID 				NUMBER(10,0),
	COMISION					NUMBER(5,2),
	COMISION_RENOVACION 		NUMBER(5,2),
	ASEG_PAGACOMISION_POR		CHAR(1),	
	NR_MAXRENOV_PARAPAGO_COM	NUMBER(2),
	VLR_MAX_COMIXIONTEC			NUMBER(20,5),
	VLR_MAX_ENDIFERENCIA_COM	NUMBER(20,5),
	SN_COMISION_XEDAD			CHAR(1),
	ADM_SUBRAMO_ID				NUMBER(10),
	EDAD_POLIZA					NUMBER(3),
	PRODUCTO_COMISION			VARCHAR2(2000) DEFAULT '',
	NOM_RAMO					VARCHAR2(200) DEFAULT '',
	NOM_PRODUCTO				VARCHAR2(200) DEFAULT '',
	NOM_MONEDA					VARCHAR2(200) DEFAULT '',
	PAGA_COMISION_POR			VARCHAR2(200) DEFAULT '',
	COMISION_EDAD_SN			VARCHAR2(200) DEFAULT '',
	PJ_COMISION_TECNICA_POR		CHAR(3) DEFAULT '',
	COMISION_POR				VARCHAR2(25) DEFAULT '',
	COMISION_COBRO              NUMBER(5,2),
	ASEGURADORA_ID              NUMBER(10),
	ASEGURADORA                 VARCHAR2(150)
) ON COMMIT PRESERVE ROWS;
/
CALL DROP_TABLE ('IBROKER','REP_TABLATEMP_COMISIONES_PARAM');
/
CREATE GLOBAL TEMPORARY TABLE REP_TABLATEMP_COMISIONES_PARAM
(
	CLIENTE_ID				    VARCHAR2(10)  DEFAULT '',
	NOM_CLIENTE				    VARCHAR2(200) DEFAULT '',
	ORGANIZACION_ID				VARCHAR2(10)  DEFAULT '',
	NOM_ORGANIZACION			VARCHAR2(200) DEFAULT ''
) ON COMMIT PRESERVE ROWS;
/

CALL DROP_PROCEDURE('SPREP_PARAM_COMISIONES')
/

CREATE PROCEDURE IBROKER.SPREP_PARAM_COMISIONES
(
	P_AD_CLIENT_ID        		IN	VARCHAR2, 
	P_AD_ORG_ID           		IN	VARCHAR2,
	P_RAMO 						IN	VARCHAR2,
	P_ASEGURADORA 				IN	VARCHAR2,
	P_TIPO_CONSULTA				IN	VARCHAR2,
	CURSOR_PAGOS				OUT	SYS_REFCURSOR
) IS
	--Declaracion de variables
	V_CONSULTA_DIM		VARCHAR2(8000);
	V_TIPO_LICENCIA 	CHAR(1);
	V_ADM_PRODUCTO_ID   NUMBER(10);
	V_RAMOS  			VARCHAR2(1100) DEFAULT '';
	V_ASEGURADORAS 		VARCHAR2(1100) DEFAULT '';
	V_AD_LANGUAGE		VARCHAR2(6);
	
BEGIN --P1 :

	--Se declara la tabla temporal REP_TABLATEMP_PARAM_COMISIONES
	DELETE FROM IBROKER.REP_TABLATEMP_PARAM_COMISIONES;
	
	--Se declara la tabla temporal REP_TABLATEMP_COMISIONES_PARAM
	DELETE FROM IBROKER.REP_TABLATEMP_COMISIONES_PARAM;
	
	BEGIN
		SELECT LICENSE_TYPE INTO V_TIPO_LICENCIA
		FROM IBROKER.C_BPARTNER_LICENSE 
		WHERE C_BPARTNER_ID = (SELECT C_BPARTNER_ID FROM IBROKER.C_BPARTNER WHERE AD_CLIENT_ID=IBROKER.TO_NUMBER(P_AD_CLIENT_ID) AND AD_ORG_ID=IBROKER.TO_NUMBER(P_AD_ORG_ID) AND BPARTNER_TYPE='000' );
	EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
	END;

	BEGIN
		SELECT COALESCE(B.AD_LANGUAGE, C.AD_LANGUAGE) INTO V_AD_LANGUAGE
		FROM IBROKER.C_BPARTNER B
		INNER JOIN IBROKER.AD_CLIENT C ON (B.AD_CLIENT_ID = C.AD_CLIENT_ID)
		WHERE B.BPARTNER_TYPE = '000' AND B.AD_CLIENT_ID = IBROKER.TO_NUMBER(P_AD_CLIENT_ID) AND B.AD_ORG_ID = IBROKER.TO_NUMBER(P_AD_ORG_ID);
	EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
	END;
	
	IF (P_RAMO = '0') THEN 
		V_RAMOS := '';
	ELSE
		V_RAMOS := ' AND P.ADM_RAMO_ID IN ('||P_RAMO||') ';
	END IF;
	
	IF (P_ASEGURADORA = '0') THEN 
		V_ASEGURADORAS := '';
	ELSE
		V_ASEGURADORAS := ' AND P.ASEGURADORA_ID IN('||P_ASEGURADORA||') ';
	END IF;
	
	IF(P_TIPO_CONSULTA = 'DETALLADO') THEN
	
		V_CONSULTA_DIM := ' INSERT INTO IBROKER.REP_TABLATEMP_PARAM_COMISIONES(ADM_RAMO_ID, ADM_PRODUCTO_ID, NOMBRE, C_CURRENCY_ID, COMISION, '
							||' COMISION_RENOVACION, ASEG_PAGACOMISION_POR, NR_MAXRENOV_PARAPAGO_COM, VLR_MAX_COMIXIONTEC, VLR_MAX_ENDIFERENCIA_COM, SN_COMISION_XEDAD, PJ_COMISION_TECNICA_POR,COMISION_COBRO,ASEGURADORA_ID) '
							||' (SELECT ADM_RAMO_ID, P.ADM_PRODUCTO_ID, NOMBRE, C_CURRENCY_ID, COMISION, COMISION_RENOVACION, E.ASEG_PAGACOMISION_POR, E.NR_MAXRENOV_PARAPAGO_COM, '
							||' E.VLR_MAX_COMIXIONTEC, E.VLR_MAX_ENDIFERENCIA_COM, P.SN_COMISION_XEDAD, P.PJ_COMISION_TECNICA_POR, P.COMISION_COBRO, P.ASEGURADORA_ID '
							||' FROM IBROKER.ADM_PRODUCTO P INNER JOIN IBROKER.ADM_PRODUCTO_EXTENSION E ON P.ADM_PRODUCTO_ID=E.ADM_PRODUCTO_ID '
							||' WHERE P.AD_CLIENT_ID = '||P_AD_CLIENT_ID
							||' AND P.AD_ORG_ID = '||P_AD_ORG_ID|| ' ';
		
		V_CONSULTA_DIM := V_CONSULTA_DIM || V_RAMOS;
		V_CONSULTA_DIM := V_CONSULTA_DIM || V_ASEGURADORAS;
		V_CONSULTA_DIM := V_CONSULTA_DIM || ') ';
		
						EXECUTE IMMEDIATE  V_CONSULTA_DIM;	
			
		IF(V_TIPO_LICENCIA = 'A') THEN
		
			UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM
			SET (PRODUCTO_COMISION ) =(
				SELECT (CASE WHEN SN_COMISION_XEDAD = 'Y' THEN (substr( LISTAGG( concat( ', ', IBROKER.TO_CHAR(COALESCE(ADM_SUBRAMO_ID, 0)) ||'-'|| IBROKER.TO_CHAR(COALESCE(COMISION, 0)) ||'%-'|| IBROKER.TO_CHAR(COALESCE(COMISION_RENOVACION, 0))||'%') ) WITHIN GROUP (ORDER BY 1), 3 )) ELSE NULL END) 
				FROM IBROKER.ADM_PRODUCTO_COMISION EDA 
				WHERE EDA.ADM_PRODUCTO_ID = COM.ADM_PRODUCTO_ID 
				group by ADM_PRODUCTO_ID);
					
		ELSE
		
			UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM
			SET (PRODUCTO_COMISION) =(
				SELECT (CASE WHEN SN_COMISION_XEDAD = 'Y' THEN (substr( LISTAGG( concat( ', ', IBROKER.TO_CHAR(COALESCE(EDAD_POLIZA, 0)) ||'-'|| IBROKER.TO_CHAR(COALESCE(COMISION, 0)))||'%')  WITHIN GROUP (ORDER BY 1), 3 )) ELSE NULL END)
				FROM IBROKER.ADM_PRODUCTO_COMISION_XEDAD 
				WHERE ADM_PRODUCTO_ID= COM.ADM_PRODUCTO_ID 
				group by ADM_PRODUCTO_ID);
			
		END IF;
		
		UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM 
		SET PRODUCTO_COMISION = (
			SELECT (substr( LISTAGG( concat(', ', (sb.NOMBRE_CORTO || ' Com. Bas. ' || IBROKER.TO_CHAR(c.COMISION)  || ' Com. Ren. ' || IBROKER.TO_CHAR(c.COMISION_RENOVACION)) ) )  WITHIN GROUP (ORDER BY 1), 3 ) ) 
			FROM IBROKER.ADM_PRODUCTO_COMISION_XCOBER c
			INNER JOIN IBROKER.ADM_SUBAMPARO sb on c.ADM_SUBAMPARO_ID=sb.ADM_SUBAMPARO_ID
			WHERE c.ADM_PRODUCTO_ID = COM.ADM_PRODUCTO_ID
		)
		WHERE COM.PJ_COMISION_TECNICA_POR = 'COB';
			
		UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM
		SET NOM_RAMO = (
			SELECT NOMBRE
			FROM IBROKER.ADM_RAMO RAM 
			WHERE RAM.ADM_RAMO_ID=COM.ADM_RAMO_ID);
			
			
		UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM
		SET NOM_PRODUCTO = (
			SELECT NOMBRE 
			FROM IBROKER.ADM_PRODUCTO PRO 
			WHERE PRO.ADM_PRODUCTO_ID=COM.ADM_PRODUCTO_ID);
			
			
		UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM
		SET NOM_MONEDA = (	
			SELECT CUR.DESCRIPTION AS MONEDA 
			FROM IBROKER.C_CURRENCY CUR 
			WHERE CUR.C_CURRENCY_ID = COM.C_CURRENCY_ID);
			

            
		UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM
        SET ASEGURADORA = (SELECT NAME FROM IBROKER.C_BPARTNER WHERE C_BPARTNER_ID=ASEGURADORA_ID);

		UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM
		SET PAGA_COMISION_POR = (IBROKER.GET_AD_REF_LIST_NAME(800645, COM.ASEG_PAGACOMISION_POR, V_AD_LANGUAGE, IBROKER.TO_NUMBER(P_AD_CLIENT_ID), IBROKER.TO_NUMBER(P_AD_ORG_ID)));
		
		
		UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM
		SET COMISION_EDAD_SN = (IBROKER.GET_AD_REF_LIST_NAME(100994, COM.SN_COMISION_XEDAD, V_AD_LANGUAGE, IBROKER.TO_NUMBER(P_AD_CLIENT_ID), IBROKER.TO_NUMBER(P_AD_ORG_ID)));
		
		
		UPDATE IBROKER.REP_TABLATEMP_PARAM_COMISIONES COM
		SET COMISION_POR = (IBROKER.GET_AD_REF_LIST_NAME(101852, COM.PJ_COMISION_TECNICA_POR, V_AD_LANGUAGE, IBROKER.TO_NUMBER(P_AD_CLIENT_ID), IBROKER.TO_NUMBER(P_AD_ORG_ID)));
							
		BEGIN --P2 :
			OPEN CURSOR_PAGOS FOR
				SELECT ADM_RAMO_ID, ADM_PRODUCTO_ID, NOMBRE, C_CURRENCY_ID, COMISION, COMISION_RENOVACION, 
				ASEG_PAGACOMISION_POR, NR_MAXRENOV_PARAPAGO_COM, VLR_MAX_COMIXIONTEC, VLR_MAX_ENDIFERENCIA_COM, SN_COMISION_XEDAD, ADM_SUBRAMO_ID, EDAD_POLIZA, 
				PRODUCTO_COMISION, NOM_RAMO, NOM_PRODUCTO, NOM_MONEDA, PAGA_COMISION_POR, COMISION_EDAD_SN, PJ_COMISION_TECNICA_POR, COMISION_POR, COMISION_COBRO, ASEGURADORA
				FROM IBROKER.REP_TABLATEMP_PARAM_COMISIONES;
		END; --P2
	
	END IF;
	
END SPREP_PARAM_COMISIONES; --P1
/
